export const FEEDBACK_MESSAGE_INFO = 'FEEDBACK_MESSAGE_INFO';
export const FEEDBACK_MESSAGE_SUCCESS = 'FEEDBACK_MESSAGE_SUCCESS';
export const FEEDBACK_MESSAGE_WARN = 'FEEDBACK_MESSAGE_WARN';
export const FEEDBACK_MESSAGE_ERROR = 'FEEDBACK_MESSAGE_ERROR';

export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_FAILED = 'SESSION_FAILED';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_ENDED = 'SESSION_ENDED';

export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';

export const CREW_REQUEST = 'CREW_REQUEST';
export const CREW_SUCCESS = 'CREW_SUCCESS';
export const CREW_FAILED = 'CREW_FAILED';

